#!/bin/sh
iam="$0"
profDir=$(dirname "$iam")
profDir=$(dirname "$profDir")
profDir="$profDir/Profile"
exec '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --app="http://trello.com" --disk-cache-dir="/dev/null/" --disk-cache-size=1 --user-data-dir="$profDir" "$@"
