#!/bin/sh
iam="$0"
profDir=$(dirname "$iam")
profDir=$(dirname "$profDir")
profDir="$profDir/Profile"
exec '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --app="http://instagram.com" --window-size=321,1015 --window-position=1590,32 --disk-cache-dir="/dev/null/" --disk-cache-size=1 --user-data-dir="$profDir" "$@"
